// extends CLAB to level 50
DEFINE_PATCH_MACRO ~extend_clab_to_level_50~ BEGIN

  REPLACE_TEXTUALLY ~[%wnl%%mnl%]+~ ~%lnl%~
  REPLACE_TEXTUALLY ~\(1[ %tab%]+2[ %tab%]+3[ %tab%]+4[ %tab%]+5[ %tab%]+6[ %tab%]+7[ %tab%]+8[ %tab%]+9[ %tab%]+10[ %tab%]+11[ %tab%]+12[ %tab%]+13[ %tab%]+14[ %tab%]+15[ %tab%]+16[ %tab%]+17[ %tab%]+18[ %tab%]+19[ %tab%]+20[ %tab%]+21[ %tab%]+22[ %tab%]+23[ %tab%]+24[ %tab%]+25[ %tab%]+26[ %tab%]+27[ %tab%]+28[ %tab%]+29[ %tab%]+30[ %tab%]+31[ %tab%]+32[ %tab%]+33[ %tab%]+34[ %tab%]+35[ %tab%]+36[ %tab%]+37[ %tab%]+38[ %tab%]+39\)\([ %tab%]+\)40[ %tab%]*~
    ~\1\240\241\242\243\244\245\246\247\248\249\250~
  REPLACE_TEXTUALLY ~^\(ABILITY[0-9A-Z]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+\)\([ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%]+[ %tab%]+[^ %tab%%lnl%]+\)[ %tab%]*$~
    ~\1\2\2~

END